### ISSUE TITLE
程序无法运行

### ISSUE THREAD

**Issue by xilinniao123** [thunlp/XQA#1]
感谢分享,有两个问题:
首先 cache_train.py 文件不存在;
其次在运行脚本dump_preprocessed_dev.py的时候报错
python dump_preprocessed_dev.py --input_file dev_data_en.pkl --output_file en_dev_output.json
的时候报错,因为在 dump_preprocessed_dev.py 中, pickle加载的 dev_data_en.pkl  对象 是 list of ExtractMultiParagraphsPerQuestion ,但 ExtractMultiParagraphsPerQuestion 没有question_id 等字段

**Comment by alphaf52** [comment]
感谢提醒，之前文件有遗漏，现在应该已经修复了。
