### ISSUE TITLE
bert预测的时候逻辑问题

### ISSUE THREAD

**Issue by helloword12345678** [thunlp/XQA#3]
run_bert_open_qa_eval.py bert做测试的时候，输入文件代表了每个样本：是一个dict，具体key是 {"question_id": "", "doc_id": "", "question": [], "context": [], "answer_text": []}
同一个question_id可以出现在多行中，也就是表示一个question可以有多个doc的;

这个数据作为test输入bert模型作预测，给每个qid+docid得到一个最优结果，

所以预测的时候并没有考虑 同一个qid的多个docs情况，也就没有比较一个qid的多个docs得分
请问这样做是否合理？

**Comment by alphaf52** [comment]
这是follow "Simple and Effective Multi-Paragraph Reading Comprehension"这篇文章（也就是DocumentQA）的处理方式，在训练的时候sample两段用shared-norm的方式进行训练，预测的时候每段单独处理得到分数，取分数最高的一个结果。这不一定是最好的处理方式，但是为了和documentQA作对比，我们也就使用了一样的方式。

**Comment by helloword12345678** [comment]
感谢回复，您说的有道理，但是我没有看到“”预测的时候每段单独处理得到分数，取分数最高的一个结果”中的取最高这个操作，请指示

**Comment by alphaf52** [comment]
run_bert_open_qa_eval.py里会给出两个输出，一个每个qid+docid的输出，叫做paragraph-prediction，还有一个是qid对应所有paragraph分数最高的输出，叫做question-prediction。这个操作在的536-542行
