### ISSUE TITLE
How is retrieval done?

### ISSUE THREAD

**Issue by tuzhucheng** [thunlp/XQA#5]
Hi, thank you for open-sourcing your great work!

I believe in your paper Document-QA and BERT (the "reader" module) are for finding the answer given a document returned by the retrieval system. In Table 7, you also report retrieval performance on the XQA dataset.

May I know which information retrieval system you used for these experiments? What is the corpus that was indexed and how are the documents in different languages indexed and ranked?

Thank you very much!

**Comment by alphaf52** [comment]
Hi, thank you for your question. The retrieval process is described in the second and the third paragraph of Section 4.1 in our paper.

Basically, we use Wikipedia dump of the same language as the question. English Wiki articles for English question, German Wiki articles for German question, etc. We remove the first paragraph of each article, and retrieve top-10 articles ranked by BM25.

**Comment by tuzhucheng** [comment]
Thanks! I missed that while reading.
