### ISSUE TITLE
Is "zh_ori" wrong or something else?

### ISSUE THREAD

**Issue by liyu-kun** [thunlp/XQA#7]
I found the tokenization of "zh" corpus not right. After I looked into the code, I found this state:
```python
if args.corpus == "en_trans_zh" or args.corpus == "zh_ori":
```
at line 140 of build_span_corpus.py and line 260 of evidence_corpus.py.

I want to know whether this is a bug or something else.

**Comment by alphaf52** [comment]
Sorry, "zh_ori" should be "zh", it's already fixed now. Thanks.
